import React, { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import Modal from '../common/Modal';
import db from '../../db/database';
import { useAuthStore } from '../../stores/authStore';
import { useToast } from '../common/Toast';
import { writeAudit } from '../../utils/audit';

export default function CategoryManager({ categories, subcategories, onChanged, onClose }) {
  const [categoryName, setCategoryName] = useState(''); const [subNames, setSubNames] = useState({});
  const staff = useAuthStore(state => state.currentStaff); const toast = useToast();
  async function addCategory() { const name = categoryName.trim(); if (!name) return; try { const id = await db.categories.add({ name, sortOrder: categories.length + 1, active: true }); await writeAudit({ action: 'CREATE', entityType: 'category', entity: name, entityId: id, staff, afterState: { name } }); setCategoryName(''); await onChanged(); } catch { toast('Category name must be unique.', 'error'); } }
  async function renameCategory(row) { const name = window.prompt('New category name', row.name)?.trim(); if (!name || name === row.name) return; const products = await db.products.query({ filters: [{ field: 'category', op: 'eq', value: row.name }] }); await Promise.all(products.map(product => db.products.update(product.id, { category: name }))); await db.categories.update(row.id, { name }); await writeAudit({ action: 'UPDATE', entityType: 'category', entity: name, entityId: row.id, staff, beforeState: row, afterState: { ...row, name } }); await onChanged(); }
  async function removeCategory(row) { const products = await db.products.query({ filters: [{ field: 'category', op: 'eq', value: row.name }] }); if (products.length) return toast(`${products.length} product(s) still use ${row.name}. Reassign them first.`, 'error'); if (!window.confirm(`Delete category ${row.name} and its unused subcategories?`)) return; const children = await db.subcategories.where('categoryId').equals(row.id).toArray(); for (const child of children) await db.subcategories.delete(child.id); await db.categories.delete(row.id); await writeAudit({ action: 'DELETE', entityType: 'category', entity: row.name, entityId: row.id, staff, beforeState: row }); await onChanged(); }
  async function addSubcategory(category) { const name = (subNames[category.id] || '').trim(); if (!name) return; try { const id = await db.subcategories.add({ categoryId: category.id, name, sortOrder: subcategories.filter(row => row.categoryId === category.id).length + 1, active: true }); await writeAudit({ action: 'CREATE', entityType: 'subcategory', entity: name, entityId: id, staff, afterState: { category: category.name, name } }); setSubNames(current => ({ ...current, [category.id]: '' })); await onChanged(); } catch { toast('Subcategory name must be unique within its category.', 'error'); } }
  async function renameSubcategory(row, category) { const name = window.prompt('New subcategory name', row.name)?.trim(); if (!name || name === row.name) return; const products = await db.products.query({ filters: [{ field: 'category', op: 'eq', value: category.name }, { field: 'subCategory', op: 'eq', value: row.name }] }); await Promise.all(products.map(product => db.products.update(product.id, { subCategory: name }))); await db.subcategories.update(row.id, { name }); await writeAudit({ action: 'UPDATE', entityType: 'subcategory', entity: name, entityId: row.id, staff, beforeState: row, afterState: { ...row, name } }); await onChanged(); }
  async function removeSubcategory(row, category) { const products = await db.products.query({ filters: [{ field: 'category', op: 'eq', value: category.name }, { field: 'subCategory', op: 'eq', value: row.name }] }); if (products.length) return toast(`${products.length} product(s) still use ${row.name}. Reassign them first.`, 'error'); if (!window.confirm(`Delete subcategory ${row.name}?`)) return; await db.subcategories.delete(row.id); await writeAudit({ action: 'DELETE', entityType: 'subcategory', entity: row.name, entityId: row.id, staff, beforeState: row }); await onChanged(); }
  return <Modal title="Manage POS Categories" large onClose={onClose} footer={<button className="btn btn-primary" onClick={onClose}>Done</button>}>
    <div className="form-row mb-16"><input className="form-input" value={categoryName} onChange={e => setCategoryName(e.target.value)} placeholder="New category"/><button className="btn btn-primary" onClick={addCategory}><Plus size={16}/> Add Category</button></div>
    <div className="category-manager">{categories.map(category => <section key={category.id}><div className="flex-between"><button className="btn btn-ghost" onClick={() => renameCategory(category)}><strong>{category.name}</strong></button><button className="btn btn-ghost btn-icon" onClick={() => removeCategory(category)}><Trash2 size={15}/></button></div>
      {subcategories.filter(row => row.categoryId === category.id).map(row => <div className="subcategory-manager-row" key={row.id}><button className="btn btn-ghost" onClick={() => renameSubcategory(row, category)}>{row.name}</button><button className="btn btn-ghost btn-icon" onClick={() => removeSubcategory(row, category)}><Trash2 size={14}/></button></div>)}
      <div className="form-row"><input className="form-input" value={subNames[category.id] || ''} onChange={e => setSubNames(current => ({ ...current, [category.id]: e.target.value }))} placeholder="New subcategory"/><button className="btn btn-secondary" onClick={() => addSubcategory(category)}><Plus size={15}/></button></div>
    </section>)}</div>
  </Modal>;
}
