-- Costing, modifiers, regulated discounts, and paid pager queue.
-- Safe to run repeatedly and preserves legacy membership, split-payment, and tab data.

alter table public.ingredients alter column "inStock" type numeric(14,4) using "inStock"::numeric(14,4);
alter table public.ingredients alter column "lowThreshold" type numeric(14,4) using "lowThreshold"::numeric(14,4);
alter table public.inventory alter column "inStock" type numeric(14,4) using "inStock"::numeric(14,4);
alter table public.product_ingredients alter column quantity type numeric(14,4) using quantity::numeric(14,4);
alter table public.product_inventory alter column quantity type numeric(14,4) using quantity::numeric(14,4);
alter table public.ingredient_movements alter column quantity type numeric(14,4) using quantity::numeric(14,4);
alter table public.ingredient_movements alter column "beforeStock" type numeric(14,4) using "beforeStock"::numeric(14,4);
alter table public.ingredient_movements alter column "afterStock" type numeric(14,4) using "afterStock"::numeric(14,4);

alter table public.staff drop constraint if exists staff_pin_four_digits;
alter table public.staff drop constraint if exists staff_pin_six_digits;
update public.staff set pin = lpad(pin, 6, '0') where pin ~ '^[0-9]{4}$';
alter table public.staff add constraint staff_pin_six_digits check (pin is null or pin ~ '^[0-9]{6}$');

alter table public.transactions
  add column if not exists "discountTotal" numeric(12,2) not null default 0,
  add column if not exists "discountAuthorizationCount" integer not null default 0;

alter table public.audit_log
  add column if not exists "entityType" text,
  add column if not exists "beforeState" jsonb,
  add column if not exists "afterState" jsonb;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  "sortOrder" integer not null default 0,
  active boolean not null default true
);
create unique index if not exists idx_categories_name_ci on public.categories (lower(name));

create table if not exists public.subcategories (
  id bigint generated by default as identity primary key,
  "categoryId" bigint not null references public.categories(id) on delete restrict,
  name text not null,
  "sortOrder" integer not null default 0,
  active boolean not null default true
);
create unique index if not exists idx_subcategories_category_name_ci on public.subcategories ("categoryId", lower(name));

insert into public.categories (name, "sortOrder") values
  ('Drinks', 1), ('Food', 2), ('Takeout Box', 3)
on conflict do nothing;
insert into public.subcategories ("categoryId", name, "sortOrder")
select c.id, seed.name, seed.sort_order
from (values
  ('Drinks','Coffee',1), ('Drinks','Non coffee',2), ('Drinks','Frappe',3),
  ('Drinks','Fruit-Blended',4), ('Drinks','Refreshing Beverage',5), ('Drinks','Milk Tea and Tea',6),
  ('Food','Starters',1), ('Food','Salad',2), ('Food','Rice Meal',3), ('Food','Pasta',4),
  ('Food','Sandwich and Burger',5), ('Food','Pizza and Quesadilla',6), ('Food','Dessert',7),
  ('Takeout Box','Takeout Box',1)
) as seed(category_name, name, sort_order)
join public.categories c on c.name = seed.category_name
on conflict do nothing;

create table if not exists public.modifier_groups (
  id bigint generated by default as identity primary key,
  "productId" bigint not null references public.products(id) on delete cascade,
  name text not null,
  required boolean not null default false,
  "selectionMode" text not null default 'single' check ("selectionMode" in ('single','multiple')),
  "minSelections" integer not null default 0 check ("minSelections" >= 0),
  "maxSelections" integer not null default 1 check ("maxSelections" >= 1),
  "sortOrder" integer not null default 0,
  active boolean not null default true
);
create index if not exists idx_modifier_groups_product on public.modifier_groups ("productId", "sortOrder");

create table if not exists public.modifier_options (
  id bigint generated by default as identity primary key,
  "groupId" bigint not null references public.modifier_groups(id) on delete cascade,
  name text not null,
  "priceDelta" numeric(12,2) not null default 0,
  "sortOrder" integer not null default 0,
  active boolean not null default true
);
create index if not exists idx_modifier_options_group on public.modifier_options ("groupId", "sortOrder");

create table if not exists public.modifier_option_ingredients (
  id bigint generated by default as identity primary key,
  "optionId" bigint not null references public.modifier_options(id) on delete cascade,
  "ingredientId" bigint not null references public.ingredients(id) on delete restrict,
  quantity numeric(14,4) not null check (quantity > 0),
  unique ("optionId", "ingredientId")
);
create table if not exists public.modifier_option_inventory (
  id bigint generated by default as identity primary key,
  "optionId" bigint not null references public.modifier_options(id) on delete cascade,
  "inventoryId" bigint not null references public.inventory(id) on delete restrict,
  quantity numeric(14,4) not null check (quantity > 0),
  unique ("optionId", "inventoryId")
);

create table if not exists public.discount_authorizations (
  id bigint generated by default as identity primary key,
  "transactionId" bigint not null references public.transactions(id) on delete cascade,
  "receiptNo" text,
  type text not null check (type in ('PWD','Senior')),
  "idNumber" text not null,
  photo text not null,
  "itemIndex" integer not null,
  "unitIndex" integer not null,
  "productName" text,
  "advertisedPercent" numeric(6,2) not null default 20,
  "effectivePercent" numeric(6,2) not null default 17.86,
  "discountAmount" numeric(12,2) not null,
  "staffId" bigint,
  "staffName" text,
  "createdAt" bigint not null,
  unique ("transactionId", "idNumber")
);
create index if not exists idx_discount_auth_transaction on public.discount_authorizations ("transactionId");

create table if not exists public.pager_state (
  id integer primary key default 1 check (id = 1),
  "lastAssigned" integer not null default 0 check ("lastAssigned" between 0 and 10),
  "updatedAt" bigint not null default 0
);
insert into public.pager_state (id, "lastAssigned", "updatedAt") values (1, 0, 0) on conflict (id) do nothing;

create table if not exists public.order_queue (
  id bigint generated by default as identity primary key,
  "checkoutKey" text not null unique,
  "transactionId" bigint references public.transactions(id) on delete set null,
  "receiptNo" text,
  "pagerNumber" integer not null check ("pagerNumber" between 1 and 10),
  status text not null default 'reserved' check (status in ('reserved','active','completed','cancelled')),
  "orderType" text,
  "staffId" bigint,
  "staffName" text,
  "reservedAt" bigint not null,
  "queuedAt" bigint,
  "pagerHandedAt" bigint,
  "completedAt" bigint,
  "durationMs" bigint
);
create unique index if not exists idx_order_queue_transaction on public.order_queue ("transactionId") where "transactionId" is not null;
create unique index if not exists idx_order_queue_active_pager on public.order_queue ("pagerNumber") where status in ('reserved','active');
create index if not exists idx_order_queue_status_time on public.order_queue (status, "queuedAt");

create table if not exists public.order_queue_items (
  id bigint generated by default as identity primary key,
  "queueId" bigint not null references public.order_queue(id) on delete cascade,
  "transactionItemIndex" integer not null,
  "unitIndex" integer not null,
  "productId" bigint,
  name text not null,
  modifiers jsonb not null default '[]'::jsonb,
  served boolean not null default false,
  "servedAt" bigint,
  "durationMs" bigint,
  unique ("queueId", "transactionItemIndex", "unitIndex")
);
create index if not exists idx_order_queue_items_queue on public.order_queue_items ("queueId");

create or replace function public.reserve_next_pager(p_checkout_key text, p_staff_id bigint default null, p_staff_name text default null)
returns table(queue_id bigint, pager_number integer)
language plpgsql
as $$
declare
  last_number integer;
  candidate integer;
  i integer;
  now_ms bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
begin
  update public.order_queue set status = 'cancelled'
  where status = 'reserved' and "reservedAt" < now_ms - 300000;

  select id, "pagerNumber" into queue_id, pager_number
  from public.order_queue where "checkoutKey" = p_checkout_key and status in ('reserved','active');
  if queue_id is not null then return next; return; end if;

  select "lastAssigned" into last_number from public.pager_state where id = 1 for update;
  for i in 1..10 loop
    candidate := ((last_number + i - 1) % 10) + 1;
    if not exists (select 1 from public.order_queue where "pagerNumber" = candidate and status in ('reserved','active')) then
      insert into public.order_queue ("checkoutKey", "pagerNumber", status, "staffId", "staffName", "reservedAt")
      values (p_checkout_key, candidate, 'reserved', p_staff_id, p_staff_name, now_ms)
      returning id into queue_id;
      update public.pager_state set "lastAssigned" = candidate, "updatedAt" = now_ms where id = 1;
      pager_number := candidate;
      return next; return;
    end if;
  end loop;
  raise exception 'All pagers are currently in use.' using errcode = 'P0001';
end;
$$;

create or replace function public.cancel_pager_reservation(p_checkout_key text)
returns void language sql as $$
  update public.order_queue set status = 'cancelled'
  where "checkoutKey" = p_checkout_key and status = 'reserved';
$$;

create or replace function public.adjust_ingredient_stock(p_ingredient_id bigint, p_delta numeric)
returns table(before_stock numeric, after_stock numeric)
language plpgsql as $$
declare current_stock numeric;
begin
  select "inStock" into current_stock from public.ingredients where id = p_ingredient_id for update;
  if current_stock is null then return; end if;
  before_stock := current_stock;
  after_stock := greatest(0, round((current_stock + p_delta)::numeric, 4));
  update public.ingredients set "inStock" = after_stock where id = p_ingredient_id;
  return next;
end;
$$;

do $$
declare tbl text;
begin
  foreach tbl in array array[
    'categories','subcategories','modifier_groups','modifier_options',
    'modifier_option_ingredients','modifier_option_inventory','discount_authorizations',
    'pager_state','order_queue','order_queue_items'
  ] loop
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', tbl);
    execute format('alter table public.%I enable row level security', tbl);
    execute format('drop policy if exists "Allow app access" on public.%I', tbl);
    execute format('create policy "Allow app access" on public.%I for all to anon, authenticated using (true) with check (true)', tbl);
  end loop;
end $$;
grant execute on function public.reserve_next_pager(text,bigint,text) to anon, authenticated;
grant execute on function public.cancel_pager_reservation(text) to anon, authenticated;
grant execute on function public.adjust_ingredient_stock(bigint,numeric) to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
